version: 2

jobs:
  build-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx firebase use --token $FIREBASE_KEY $TARGET_ENVIRONMENT
      - run: npx firebase deploy --token $FIREBASE_KEY

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy
